name: CI

on: workflow_call

jobs:
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Restore Cache
        uses: actions/cache@v2
        id: cache
        with:
          path: ~/.cache/pip
          key: pip-${{ hashFiles('pyproject.toml') }}
          restore-keys: pip-

      - name: Install Dependencies
        run: pip install poetry

      - name: Install Package
        run: poetry install

      - name: Static Type Checking
        run: poetry run python -m mypy .

      - name: Run Tests
        run: poetry run python -m pytest .